version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      day: "monday"
      time: "05:00"
      timezone: "America/Chicago"
    # Project not actively developed, so only allow security updates and personal projects
    allow:
      - dependency-name: "pyngrok"