language: python
python:
  - "2.7"
  - "3.6"
install:
  - pip install virtualenv
  - python -m virtualenv .venv
  - source .venv/bin/activate
  - easy_install distribute
  - pip install -r requirements.txt
script: make env test
after_success:
  - codecov