FROM helium/platform

RUN apt-get install -y supervisor

COPY container/supervisord.conf /etc/supervisor
COPY container/supervisor-celerybeat.conf /etc/supervisor/conf.d/celerybeat.conf
COPY container/supervisor-celeryworker.conf /etc/supervisor/conf.d/celeryworker.conf

CMD ["supervisord", "-c", "/etc/supervisor/supervisord.conf", "-n"]
