services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "platform_dev-local"
      MYSQL_USER: "helium"
      MYSQL_PASSWORD: "helium"
    ports:
      - 3306:3306
    container_name: helium_db
  cache:
    image: redis:7.2
    ports:
      - 6379:6379
    container_name: helium_cache
  storage:
    image: localstack/localstack:s3-latest
    environment:
      ENVIRONMENT: "dev-local"
    ports:
      - 4566:4566
    volumes:
      - "./container/init-localstack.py:/etc/localstack/init/ready.d/init-localstack.py"
    container_name: helium_storage
  resource:
    image: helium/platform-resource
    env_file: .env
    volumes:
      - type: bind
        source: ./.env
        target: /app/.env
    container_name: helium_platform_resource
    depends_on:
      - db
      - cache
      - storage
  api:
    image: helium/platform-api
    env_file: .env
    volumes:
      - type: bind
        source: ./.env
        target: /app/.env
    ports:
      - 8000:8000
    container_name: helium_platform_api
    depends_on:
      - db
      - cache
      - storage
  worker:
    image: helium/platform-worker
    environment:
        PLATFORM_BEAT_AND_WORKER_MODE: "True"
    env_file: .env
    volumes:
      - type: bind
        source: ./.env
        target: /app/.env
    container_name: helium_platform_worker
    depends_on:
      - db
      - cache
      - storage
