services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "platform_dev-local"
      MYSQL_USER: "helium"
      MYSQL_PASSWORD: "helium"
    ports:
      - 3306:3306
    healthcheck:
        test: "mysql $$MYSQL_DATABASE -u$$MYSQL_USER -p$$MYSQL_PASSWORD -e 'SELECT 1;'"
        timeout: 3s
        retries: 20
  cache:
    image: redis:7.2
    ports:
      - 6379:6379
  storage:
    image: localstack/localstack:s3-latest
    environment:
      ENVIRONMENT: "dev-local"
    ports:
      - 4566:4566
    volumes:
      - "./container/init-localstack.py:/etc/localstack/init/ready.d/init-localstack.py"
  resource:
    image: helium/platform-resource
    env_file: .env
    volumes:
      - type: bind
        source: ./.env
        target: /app/.env
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started
      storage:
        condition: service_healthy
  api:
    image: helium/platform-api
    env_file: .env
    volumes:
      - type: bind
        source: ./.env
        target: /app/.env
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started
      storage:
        condition: service_healthy
      resource:
        condition: service_completed_successfully
  worker:
    image: helium/platform-worker
    environment:
        PLATFORM_BEAT_AND_WORKER_MODE: "True"
    env_file: .env
    volumes:
      - type: bind
        source: ./.env
        target: /app/.env
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started
      storage:
        condition: service_healthy
      resource:
        condition: service_completed_successfully
