services:
  db:
    image: mysql:8.0
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "platform_dev"
      MYSQL_USER: "helium"
      MYSQL_PASSWORD: "helium"
    restart: always
    container_name: helium_db
  cache:
    image: redis:7.2
    restart: always
    container_name: helium_cache
  storage:
    image: localstack/localstack
    ports:
      - 4566:4566
    volumes:
      - "./container/init-localstack.py:/etc/localstack/init/ready.d/init-localstack.py"
    container_name: helium_storage
  server:
    image: helium:platform
    env_file: .env
    volumes:
      - type: bind
        source: ./.env
        target: /app/.env
    ports:
      - 80:80
    entrypoint: [ "/bin/sh","-c" ]
    command:
      - |
        sleep 15
        /usr/local/venvs/platform/bin/python manage.py collectstatic --noinput
        /usr/local/venvs/platform/bin/python manage.py migrate
        chown -R www-data:www-data /var/log/helium /var/log/apache2 
        service supervisor start; apache2ctl -D FOREGROUND
    container_name: helium_platform
    depends_on:
      - db
      - cache
      - storage
