# Generated by Django 4.2.30 on 2026-04-17 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helium_common', '0002_taskresultproxy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskresultproxy',
            options={'verbose_name': 'Task result event', 'verbose_name_plural': 'Task results events'},
        ),
        migrations.RenameIndex(
            model_name='emailreputationevent',
            new_name='helium_comm_email_d1f172_idx',
            old_name='helium_comm_email_event_type_idx',
        ),
    ]
