# Generated by Django 5.2.17 on 2026-10-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium_common', '0003_alter_taskresultproxy_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_on', models.DateField(help_text='The UTC date the value applies to.')),
                ('metric', models.CharField(help_text='The metric the value belongs to, e.g. `users.cumulative`.', max_length=255)),
                ('dimension', models.CharField(help_text='Comma-separated `key:value` pairs qualifying the value, e.g. `milestone:30d,staff:false`.', max_length=255)),
                ('value', models.FloatField(default=0, help_text='The recorded value.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('recorded_on', 'metric', 'dimension'),
                'constraints': [models.UniqueConstraint(fields=('recorded_on', 'metric', 'dimension'), name='unique_metric_sample')],
            },
        ),
    ]
