# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-03 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20180202_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalcalendar',
            name='color',
            field=models.CharField(choices=[('#ac725e', '#ac725e'), ('#d06b64', '#d06b64'), ('#f83a22', '#f83a22'), ('#fa573c', '#fa573c'), ('#ff7537', '#ff7537'), ('#ffad46', '#ffad46'), ('#42d692', '#42d692'), ('#16a765', '#16a765'), ('#7bd148', '#7bd148'), ('#b3dc6c', '#b3dc6c'), ('#fad165', '#fad165'), ('#92e1c0', '#92e1c0'), ('#9fe1e7', '#9fe1e7'), ('#9fc6e7', '#9fc6e7'), ('#4986e7', '#4986e7'), ('#9a9cff', '#9a9cff'), ('#b99aff', '#b99aff'), ('#c2c2c2', '#c2c2c2'), ('#cabdbf', '#cabdbf'), ('#cca6ac', '#cca6ac'), ('#f691b2', '#f691b2'), ('#cd74e6', '#cd74e6'), ('#a47ae2', '#a47ae2'), ('#555', '#555')], default='#4986e7', help_text='A valid hex color code choice to determine the color items will be shown on the calendar', max_length=7),
        ),
        migrations.AlterField(
            model_name='externalcalendar',
            name='shown_on_calendar',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether or not items should be shown on the calendar.'),
        ),
        migrations.AlterField(
            model_name='externalcalendar',
            name='title',
            field=models.CharField(db_index=True, help_text='A display name.', max_length=255),
        ),
        migrations.AlterField(
            model_name='externalcalendar',
            name='url',
            field=models.URLField(help_text='A public-facing URL to a valid ICAL feed.', max_length=3000),
        ),
    ]
