# Generated by Django 2.0.5 on 2018-05-15 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20180403_2152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externalcalendar',
            options={'ordering': ('title',)},
        ),
    ]
