# Generated by Django 2.2.28 on 2023-11-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20180515_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalcalendar',
            name='last_index',
            field=models.DateTimeField(blank=True, db_index=True, help_text='The last time this calendar was indexed to the cache.', null=True),
        ),
    ]
