# Generated by Django 4.2.25 on 2025-11-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_alter_externalcalendar_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalcalendar',
            name='shown_on_calendar',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether items should be shown on the calendar.'),
        ),
    ]
