# Generated by Django 4.2.26 on 2025-11-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_alter_externalcalendar_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalcalendar',
            name='example_schedule',
            field=models.BooleanField(default=False, help_text='Whether it is part of the example schedule.'),
        ),
    ]
