# Generated by Django 4.2.28 on 2026-02-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_externalcalendar_example_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalcalendar',
            name='etag',
            field=models.CharField(blank=True, help_text='The ETag header from the last successful iCal fetch.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='externalcalendar',
            name='last_modified_header',
            field=models.CharField(blank=True, help_text='The Last-Modified header from the last successful iCal fetch.', max_length=255, null=True),
        ),
    ]
