# Generated by Django 4.2.29 on 2026-04-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_add_etag_and_last_modified_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalcalendar',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='externalcalendar',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
