# Generated by Django 4.2.29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_alter_externalcalendar_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalcalendar',
            name='last_sync_error',
            field=models.TextField(blank=True, help_text='Error message from the most recent failed sync attempt, if any.', null=True),
        ),
    ]
