# Generated by Django 4.2.30 on 2026-04-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0012_externalcalendar_last_sync_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalcalendar',
            name='consecutive_failures',
            field=models.PositiveIntegerField(default=0, help_text='Number of consecutive reindex failures. Resets to 0 on success.'),
        ),
    ]
