# Generated by Django 5.2.14 on 2026-05-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0013_externalcalendar_consecutive_failures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalcalendar',
            name='url',
            field=models.URLField(help_text='A public-facing URL to a valid iCal feed. On create and on URL change, the server fetches the URL and validates the response is a parseable iCal feed; unreachable or invalid feeds are rejected at write time.', max_length=3000),
        ),
    ]
