# Generated by Django 5.2.14 on 2026-06-03 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0014_alter_externalcalendar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalcalendar',
            name='url',
            field=models.URLField(help_text='A public-facing URL to a valid iCal feed.', max_length=3000),
        ),
    ]
