# Generated by Django 5.2.16 on 2026-08-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0015_alter_externalcalendar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalcalendar',
            name='last_sync_error',
            field=models.TextField(blank=True, help_text='Error message from the most recent failed sync attempt.', null=True),
        ),
    ]
