# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-02 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helium_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='events_private_slug',
        ),
    ]
