# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-07 22:27
from __future__ import unicode_literals

from django.db import migrations, models

import helium.auth.utils.userutils


class Migration(migrations.Migration):

    dependencies = [
        ('helium_auth', '0003_auto_20180209_0255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_carrier',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_carrier_changing',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_verification_code',
            field=models.PositiveIntegerField(default=helium.auth.utils.userutils.generate_phone_verification_code, help_text=b'The code sent to `phone` when registering or changing a phone number'),
        ),
    ]
