# Generated by Django 4.2.15 on 2024-10-12 00:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium_auth', '0005_auto_20180403_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Sorry, that username is already in use.'}, help_text='A unique name used to login to the system.', max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.+-]+$', 'Enter a valid username, which means less than 30 characters consisting of letters, numbers, or these symbols: +-_.', 'invalid')]),
        ),
    ]
