# Generated by Django 4.2.20 on 2025-09-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium_auth', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='mobile_default_view',
            field=models.PositiveIntegerField(choices=[(0, 'Month'), (1, 'Week'), (2, 'Day'), (3, 'List')], default=1, help_text='A valid default mobile calendar view choice.'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='default_reminder_type',
            field=models.PositiveIntegerField(choices=[(0, 'Popup'), (1, 'Email'), (2, 'Text'), (3, 'Push')], default=0, help_text='A valid default type of reminder choice when creating a new reminder.'),
        ),
    ]
