# Generated by Django 4.2.24 on 2025-09-15 21:46

from django.db import migrations, models
import helium.auth.utils.userutils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('helium_auth', '0007_usersettings_mobile_default_view_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.SlugField(default=uuid.uuid4, help_text='The code sent to `email` when registering or changing an email address.', unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_verification_code',
            field=models.PositiveIntegerField(default=helium.auth.utils.userutils.generate_phone_verification_code, help_text='The code sent to `phone` when registering or changing a phone number.'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='events_color',
            field=models.CharField(choices=[('#ac725e', '#ac725e'), ('#d06b64', '#d06b64'), ('#f83a22', '#f83a22'), ('#fa573c', '#fa573c'), ('#ff7537', '#ff7537'), ('#ffad46', '#ffad46'), ('#42d692', '#42d692'), ('#16a765', '#16a765'), ('#7bd148', '#7bd148'), ('#b3dc6c', '#b3dc6c'), ('#fad165', '#fad165'), ('#92e1c0', '#92e1c0'), ('#9fe1e7', '#9fe1e7'), ('#9fc6e7', '#9fc6e7'), ('#4986e7', '#4986e7'), ('#9a9cff', '#9a9cff'), ('#b99aff', '#b99aff'), ('#c2c2c2', '#c2c2c2'), ('#cabdbf', '#cabdbf'), ('#cca6ac', '#cca6ac'), ('#f691b2', '#f691b2'), ('#cd74e6', '#cd74e6'), ('#a47ae2', '#a47ae2'), ('#555', '#555')], default='#ffad46', help_text='A valid hex color code choice to determine the color events will be shown on the calendar.', max_length=7),
        ),
    ]
