# Generated by Django 4.2.24 on 2025-09-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium_auth', '0008_alter_user_verification_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='firebase_token',
            field=models.CharField(blank=True, help_text='A valid Firebase token for user push notifications.', max_length=4096, null=True),
        ),
    ]
