# Generated by Django 4.2.24 on 2025-09-16 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helium_auth', '0008_alter_user_verification_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPushToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.CharField(help_text='The unique identifier for the device linked to this token.', max_length=100)),
                ('token', models.TextField(help_text='The token used for push notifications.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User push tokens',
            },
        ),
    ]
