# Generated by Django 4.2.25 on 2025-10-11 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium_auth', '0009_userpushtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='calendar_event_limit',
            field=models.BooleanField(default=True, help_text='Whether or not calendar events should collapse to "+ more" when a day is full.'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='default_view',
            field=models.PositiveIntegerField(choices=[(0, 'Month'), (1, 'Week'), (2, 'Day'), (3, 'List'), (4, 'Agenda')], default=0, help_text='A valid default calendar view choice.'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='mobile_default_view',
            field=models.PositiveIntegerField(choices=[(0, 'Month'), (1, 'Week'), (2, 'Day'), (3, 'List'), (4, 'Agenda')], default=1, help_text='A valid default mobile calendar view choice.'),
        ),
    ]
