# Generated by Django 4.2.25 on 2025-10-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium_auth', '0010_usersettings_calendar_event_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='remember_filter_state',
            field=models.BooleanField(default=True, help_text='Remember filter states for the Calendar within a session.'),
        ),
    ]
