# Generated by Django 4.2.25 on 2025-10-22 19:02

from django.db import migrations, models
import helium.auth.utils.userutils


class Migration(migrations.Migration):

    dependencies = [
        ('helium_auth', '0011_usersettings_remember_filter_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.SlugField(default=helium.auth.utils.userutils.generate_verification_code, help_text='The code sent to `email` when registering or changing an email address.'),
        ),
    ]
