# Generated by Django 4.2.25 on 2025-10-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium_auth', '0012_alter_user_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='grade_color',
            field=models.CharField(choices=[('#ac725e', '#ac725e'), ('#d06b64', '#d06b64'), ('#f83a22', '#f83a22'), ('#fa573c', '#fa573c'), ('#ff7537', '#ff7537'), ('#ffad46', '#ffad46'), ('#42d692', '#42d692'), ('#16a765', '#16a765'), ('#7bd148', '#7bd148'), ('#b3dc6c', '#b3dc6c'), ('#fad165', '#fad165'), ('#92e1c0', '#92e1c0'), ('#9fe1e7', '#9fe1e7'), ('#9fc6e7', '#9fc6e7'), ('#4986e7', '#4986e7'), ('#9a9cff', '#9a9cff'), ('#b99aff', '#b99aff'), ('#c2c2c2', '#c2c2c2'), ('#cabdbf', '#cabdbf'), ('#cca6ac', '#cca6ac'), ('#f691b2', '#f691b2'), ('#cd74e6', '#cd74e6'), ('#a47ae2', '#a47ae2'), ('#555', '#555')], default='#9a9cff', help_text='A valid hex color code choice to determine the color grade badges will be.', max_length=7),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='material_color',
            field=models.CharField(choices=[('#ac725e', '#ac725e'), ('#d06b64', '#d06b64'), ('#f83a22', '#f83a22'), ('#fa573c', '#fa573c'), ('#ff7537', '#ff7537'), ('#ffad46', '#ffad46'), ('#42d692', '#42d692'), ('#16a765', '#16a765'), ('#7bd148', '#7bd148'), ('#b3dc6c', '#b3dc6c'), ('#fad165', '#fad165'), ('#92e1c0', '#92e1c0'), ('#9fe1e7', '#9fe1e7'), ('#9fc6e7', '#9fc6e7'), ('#4986e7', '#4986e7'), ('#9a9cff', '#9a9cff'), ('#b99aff', '#b99aff'), ('#c2c2c2', '#c2c2c2'), ('#cabdbf', '#cabdbf'), ('#cca6ac', '#cca6ac'), ('#f691b2', '#f691b2'), ('#cd74e6', '#cd74e6'), ('#a47ae2', '#a47ae2'), ('#555', '#555')], default='#ffad46', help_text='A valid hex color code choice to determine the color material badges will be.', max_length=7),
        ),
    ]
