# Generated by Django 4.2.25 on 2025-11-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium_auth', '0015_alter_usersettings_calendar_event_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='calendar_use_category_colors',
            field=models.BooleanField(default=False, help_text='Whether calendar items for classes should be shown in category colors instead of class colors.'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='calendar_event_limit',
            field=models.BooleanField(default=False, help_text='Whether calendar events should collapse to "+ more" when a day is full.'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='receive_emails_from_admin',
            field=models.BooleanField(default=True, help_text='Whether the user wants to receive Helium update emails.'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='show_getting_started',
            field=models.BooleanField(default=True, help_text='Whether the "Getting Started" dialog should be shown.'),
        ),
    ]
