# Generated by Django 4.2.25 on 2025-11-05 23:17

from django.db import migrations, models
import helium.common.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('helium_auth', '0016_usersettings_calendar_use_category_colors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='events_color',
            field=models.CharField(default='#87b8d4', help_text='A valid hex color code choice to determine the color events will be shown on the calendar.', max_length=7, validators=[helium.common.utils.validators.validate_hex_color]),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='grade_color',
            field=models.CharField(default='#a387d4', help_text='A valid hex color code choice to determine the color grade badges will be.', max_length=7, validators=[helium.common.utils.validators.validate_hex_color]),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='material_color',
            field=models.CharField(default='#b8d487', help_text='A valid hex color code choice to determine the color material badges will be.', max_length=7, validators=[helium.common.utils.validators.validate_hex_color]),
        ),
    ]
