# Generated by Django 4.2.26 on 2025-11-09 14:41

from django.db import migrations, models
import helium.common.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('helium_auth', '0017_alter_usersettings_events_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='events_color',
            field=models.CharField(default='#e74674', help_text='A valid hex color code choice to determine the color events will be shown on the calendar.', max_length=7, validators=[helium.common.utils.validators.validate_hex_color]),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='grade_color',
            field=models.CharField(default='#9d629d', help_text='A valid hex color code choice to determine the color grade badges will be.', max_length=7, validators=[helium.common.utils.validators.validate_hex_color]),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='material_color',
            field=models.CharField(default='#dc7d50', help_text='A valid hex color code choice to determine the color material badges will be.', max_length=7, validators=[helium.common.utils.validators.validate_hex_color]),
        ),
    ]
