# Generated by Django 4.2.26 on 2025-11-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium_auth', '0020_alter_usersettings_time_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='default_reminder_type',
            field=models.PositiveIntegerField(choices=[(0, 'Popup'), (1, 'Email'), (2, 'Text'), (4, 'Push')], default=0, help_text='A valid default type of reminder choice when creating a new reminder.'),
        ),
    ]
