# Generated by Django 4.2.26 on 2025-12-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium_auth', '0022_alter_usersettings_default_reminder_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='default_mobile_reminder_offset_type',
            field=models.PositiveIntegerField(choices=[(0, 'minutes'), (1, 'hours'), (2, 'days'), (3, 'weeks')], default=0, help_text='A valid default type of time offset choice when creating a new reminder on mobile.'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='default_mobile_reminder_type',
            field=models.PositiveIntegerField(choices=[(0, 'Popup'), (1, 'Email'), (2, 'Text'), (3, 'Push')], default=0, help_text='A valid default type of reminder choice when creating a new reminder on mobile.'),
        ),
    ]
