# Generated by Django 4.2.26 on 2025-12-13 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium_auth', '0023_usersettings_default_mobile_reminder_offset_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersettings',
            old_name='default_mobile_reminder_offset_type',
            new_name='mobile_default_reminder_offset_type',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='default_mobile_reminder_type',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='mobile_default_reminder_type',
            field=models.PositiveIntegerField(choices=[(0, 'Popup'), (1, 'Email'), (2, 'Text'), (3, 'Push')], default=3, help_text='A valid default type of reminder choice when creating a new reminder on mobile.'),
        ),
    ]
