# Generated by Django 4.2.26 on 2025-12-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium_auth', '0024_rename_default_mobile_reminder_offset_type_usersettings_mobile_default_reminder_offset_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='mobile_default_reminder_offset',
            field=models.PositiveIntegerField(default=30, help_text='The default offset when creating a new reminder on mobile.'),
        ),
    ]
