# Generated by Django 4.2.26 on 2025-12-14 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium_auth', '0025_usersettings_mobile_default_reminder_offset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='mobile_default_view',
            field=models.PositiveIntegerField(choices=[(0, 'Month'), (1, 'Week'), (2, 'Day'), (3, 'List')], default=1, help_text='A valid default mobile calendar view choice.'),
        ),
    ]
