# Generated by Django 4.2.26 on 2026-01-22 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helium_auth', '0026_alter_usersettings_mobile_default_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='mobile_default_reminder_offset',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='mobile_default_reminder_offset_type',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='mobile_default_reminder_type',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='mobile_default_view',
        ),
    ]
