# Generated by Django 4.2.26 on 2026-01-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium_auth', '0027_remove_usersettings_mobile_default_reminder_offset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='color_scheme_theme',
            field=models.PositiveIntegerField(choices=[(0, 'Light'), (1, 'Dark'), (2, 'System')], default=1, help_text='A valid color scheme theme.'),
        ),
    ]
