# Generated by Django 4.2.26 on 2026-02-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium_auth', '0029_usersettings_whats_new_version_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='color_scheme_theme',
            field=models.PositiveIntegerField(choices=[(0, 'Light'), (1, 'Dark'), (2, 'System')], default=2, help_text='A valid color scheme theme.'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='default_reminder_type',
            field=models.PositiveIntegerField(choices=[(0, 'Popup'), (1, 'Email'), (2, 'Text'), (3, 'Push')], default=3, help_text='A valid default type of reminder choice when creating a new reminder.'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='default_view',
            field=models.PositiveIntegerField(choices=[(0, 'Month'), (1, 'Week'), (2, 'Day'), (3, 'List'), (4, 'Agenda')], default=2, help_text='A valid default calendar view choice.'),
        ),
    ]
