# Generated by Django 4.2.26 on 2026-02-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium_auth', '0030_alter_usersettings_color_scheme_theme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='default_view',
            field=models.PositiveIntegerField(choices=[(0, 'Month'), (1, 'Week'), (2, 'Day'), (3, 'List'), (4, 'Agenda')], default=0, help_text='A valid default calendar view choice.'),
        ),
    ]
