# Generated by Django 4.2.25 on 2025-02-15 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helium_auth', '0031_alter_usersettings_default_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOAuthProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('apple', 'Apple')], help_text='The OAuth provider (Google, Apple, etc.)', max_length=50)),
                ('provider_user_id', models.CharField(help_text='The unique user ID from the OAuth provider (Firebase UID)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this provider was first linked to the account')),
                ('last_used_at', models.DateTimeField(auto_now=True, help_text='When this provider was last used to sign in')),
                ('user', models.ForeignKey(help_text='The user this OAuth provider is linked to', on_delete=django.db.models.deletion.CASCADE, related_name='oauth_providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OAuth Provider',
                'verbose_name_plural': 'OAuth Providers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='useroauthprovider',
            constraint=models.UniqueConstraint(fields=('user', 'provider'), name='unique_user_provider'),
        ),
        migrations.AddConstraint(
            model_name='useroauthprovider',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_user_id'), name='unique_provider_uid'),
        ),
    ]
