# Generated by Django 4.2.28 on 2026-02-16 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helium_auth', '0032_useroauthprovider'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='useroauthprovider',
            name='unique_user_provider',
        ),
        migrations.RemoveConstraint(
            model_name='useroauthprovider',
            name='unique_provider_uid',
        ),
        migrations.AlterUniqueTogether(
            name='useroauthprovider',
            unique_together={('provider', 'provider_user_id'), ('user', 'provider')},
        ),
    ]
