# Generated by Django 4.2.29 on 2026-03-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium_auth', '0037_usersettings_drag_and_drop_on_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_legacy',
            field=models.DateTimeField(blank=True, help_text='Last login time via legacy frontend.', null=True),
        ),
    ]
