# Generated by Django 4.2.29 on 2026-03-19

from django.db import migrations, models


def backfill_last_activity(apps, schema_editor):
    """Backfill last_activity with created_at for existing users."""
    User = apps.get_model('helium_auth', 'User')
    User.objects.filter(last_activity__isnull=True).update(last_activity=models.F('created_at'))


def reverse_backfill(apps, schema_editor):
    """Reverse: set last_activity back to null."""
    User = apps.get_model('helium_auth', 'User')
    User.objects.update(last_activity=None)


class Migration(migrations.Migration):

    dependencies = [
        ('helium_auth', '0038_user_last_login_legacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text='Last user activity (login or token refresh).',
                null=True,
            ),
        ),
        migrations.RunPython(backfill_last_activity, reverse_backfill),
    ]
