# Generated by Django 4.2.29 on 2026-03-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium_auth', '0039_user_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deletion_warning_count',
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text='Number of deletion warning emails sent due to inactivity (0-4). Resets on login.',
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='deletion_warning_sent_at',
            field=models.DateTimeField(
                blank=True,
                help_text='When the last deletion warning email was sent.',
                null=True,
            ),
        ),
    ]
