# Generated by Django 4.2.30 on 2026-04-17 23:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium_auth', '0051_userclientactivity_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blacklistedtokenproxy',
            options={'verbose_name': 'Token (blacklist)', 'verbose_name_plural': 'Tokens (blacklist)'},
        ),
        migrations.AlterModelOptions(
            name='outstandingtokenproxy',
            options={'verbose_name': 'Token (outstanding)', 'verbose_name_plural': 'Tokens (outstanding)'},
        ),
        migrations.AlterModelOptions(
            name='userclientactivity',
            options={'verbose_name_plural': 'User client activities'},
        ),
        migrations.AlterModelOptions(
            name='useroauthprovider',
            options={'ordering': ['-created_at'], 'verbose_name': 'OAuth provider', 'verbose_name_plural': 'OAuth providers'},
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='at_risk_threshold',
            field=models.PositiveIntegerField(default=70, help_text='The grade percentage below which a course is flagged as at-risk.', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='on_track_tolerance',
            field=models.PositiveIntegerField(default=10, help_text='The percentage tolerance within which a course grade is considered on track.', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
