# Generated by Django 4.2.30 on 2026-04-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium_auth', '0052_alter_blacklistedtokenproxy_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersettings',
            old_name='review_prompts_shown',
            new_name='review_prompts_requested',
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='review_prompts_requested',
            field=models.PositiveIntegerField(default=0, help_text='The number of times the system has requested a review prompt from the native OS (not guaranteed to have shown a prompt).'),
        ),
    ]
