# Generated by Django 5.2.14 on 2026-05-15 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium_auth', '0059_alter_usersettings_time_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Sorry, that username is already in use.'}, help_text='A unique name used to log in to the system.', max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.+-]+$', 'Enter a valid username, which means less than 30 characters consisting of letters, numbers, or these symbols: +-_.', 'invalid')]),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='week_starts_on',
            field=models.PositiveIntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], default=0, help_text='A valid choice for the day on which the week starts.'),
        ),
    ]
