# Generated by Django 5.2.14 on 2026-05-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium_auth', '0060_alter_user_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='default_reminder_type',
            field=models.PositiveIntegerField(choices=[(1, 'Email'), (3, 'Push')], default=3, help_text='A valid default type of reminder choice when creating a new reminder.'),
        ),
    ]
