# Generated by Django 5.2.14 on 2026-05-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium_auth', '0061_alter_usersettings_color_scheme_theme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useroauthprovider',
            name='provider',
            field=models.CharField(choices=[('google', 'Google'), ('apple', 'Apple'), ('microsoft', 'Microsoft')], help_text='The OAuth provider (Google, Apple, etc.)', max_length=50),
        ),
    ]
