# Generated by Django 5.2.14 on 2026-05-30 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium_auth', '0062_alter_useroauthprovider_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useroauthprovider',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this provider was first linked to the account.'),
        ),
        migrations.AlterField(
            model_name='useroauthprovider',
            name='last_used_at',
            field=models.DateTimeField(auto_now=True, help_text='When this provider was last used to sign in.'),
        ),
        migrations.AlterField(
            model_name='useroauthprovider',
            name='provider',
            field=models.CharField(choices=[('google', 'Google'), ('apple', 'Apple'), ('microsoft', 'Microsoft')], help_text='The OAuth provider.', max_length=50),
        ),
        migrations.AlterField(
            model_name='useroauthprovider',
            name='provider_user_id',
            field=models.CharField(help_text='The unique user ID from the OAuth provider.', max_length=255),
        ),
        migrations.AlterField(
            model_name='useroauthprovider',
            name='user',
            field=models.ForeignKey(help_text='The user this OAuth provider is linked to.', on_delete=django.db.models.deletion.CASCADE, related_name='oauth_providers', to=settings.AUTH_USER_MODEL),
        ),
    ]
