# Generated by Django 5.2.14 on 2026-05-29 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium_auth', '0066_remove_userprofile_and_last_login_legacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Sorry, that username is already in use.'}, help_text='A unique name used to login to the system.', max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.+-]+$', 'Enter a valid username, which means less than 30 characters consisting of letters, numbers, or these symbols: +-_.', 'invalid')]),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='default_reminder_type',
            field=models.PositiveIntegerField(choices=[(1, 'Email'), (3, 'Push')], default=3, help_text='The reminder type pre-selected when creating a new reminder.'),
        ),
    ]
