# Generated by Django 5.2.17 on 2026-08-30 21:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium_auth', '0068_backfill_usersettings_default_reminder_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='default_reminder_offset',
            field=models.PositiveIntegerField(default=30, help_text='The default offset when creating a new reminder.', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
