# Generated by Django 5.2.17 on 2026-09-17 21:21

import helium.common.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium_auth', '0069_alter_usersettings_default_reminder_offset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='default_view',
            field=models.PositiveIntegerField(choices=[(0, 'Month'), (1, 'Week'), (2, 'Day'), (3, 'List'), (4, 'Agenda')], default=0, help_text='The view shown by default when opening the Planner.'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='material_color',
            field=models.CharField(default='#dc7d50', help_text='A valid hex color code choice to determine the color resource badges will be.', max_length=7, validators=[helium.common.utils.validators.validate_hex_color]),
        ),
    ]
