# Generated by Django 5.2.17 on 2026-09-20 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium_auth', '0070_resource_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='date_format',
            field=models.PositiveIntegerField(choices=[(0, 'Month/Day/Year'), (1, 'Day/Month/Year'), (2, 'Year/Month/Day')], default=0, help_text='The order in which day, month, and year are shown in dates.'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='number_format',
            field=models.PositiveIntegerField(choices=[(0, 'Point'), (1, 'Comma')], default=0, help_text='The decimal separator shown in grades and other numbers.'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='time_format',
            field=models.PositiveIntegerField(choices=[(0, '12-hour'), (1, '24-hour')], default=0, help_text='The clock on which times are shown.'),
        ),
    ]
