# Generated by Django 5.2.17 on 2026-09-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium_auth', '0073_usersettings_setup_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='default_view',
            field=models.PositiveIntegerField(choices=[(0, 'Month'), (1, 'Week'), (5, '3-Day'), (2, 'Day'), (3, 'List'), (4, 'Agenda')], default=0, help_text='The view shown by default when opening the Planner.'),
        ),
    ]
