# Generated by Django 5.2.17 on 2026-10-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium_auth', '0075_user_example_schedule_imported_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='getting_started_last_shown_at',
            field=models.DateTimeField(blank=True, help_text='When the "Getting Started" dialog was last shown.', null=True),
        ),
    ]
