# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-28 00:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, default=b'', max_length=255)),
                ('status', models.PositiveIntegerField(choices=[(0, b'Owned'), (1, b'Rented'), (2, b'Ordered'), (3, b'Shipped'), (4, b'Need'), (5, b'Received'), (6, b'To Sell')], default=0)),
                ('condition', models.PositiveIntegerField(choices=[(0, b'Brand New'), (1, b'Refurbished'), (2, b'Used - Like New'), (3, b'Used - Very Good'), (4, b'Used - Good'), (5, b'Used - Acceptable'), (6, b'Used - Poor'), (7, b'Broken')], default=0)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.TextField(blank=True, default=b'')),
                ('seller_details', models.TextField(blank=True, default=b'')),
                ('courses', models.ManyToManyField(blank=True, default=None, related_name='materials', to='planner.Course')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='MaterialGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, default=b'', max_length=255)),
                ('shown_on_calendar', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='material',
            name='material_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='planner.MaterialGroup'),
        ),
    ]
