# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-01 04:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='from_admin',
        ),
    ]
