# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-01 23:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('planner', '0002_remove_reminder_from_admin'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set([('course', 'title')]),
        ),
    ]
