# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-02 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('planner', '0003_category_course_title_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateField(db_index=True, help_text=b'An ISO-8601 date.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(db_index=True, help_text=b'An ISO-8601 date.'),
        ),
        migrations.AlterField(
            model_name='coursegroup',
            name='end_date',
            field=models.DateField(db_index=True, help_text=b'An ISO-8601 date.'),
        ),
        migrations.AlterField(
            model_name='coursegroup',
            name='shown_on_calendar',
            field=models.BooleanField(db_index=True, default=True,
                                      help_text=b'Whether or not items should be shown on the calendar.'),
        ),
        migrations.AlterField(
            model_name='coursegroup',
            name='start_date',
            field=models.DateField(db_index=True, help_text=b'An ISO-8601 date.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(db_index=True, help_text=b'An ISO-8601 date.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(db_index=True, help_text=b'An ISO-8601 date.'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='end',
            field=models.DateTimeField(db_index=True, help_text=b'An ISO-8601 date.'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='start',
            field=models.DateTimeField(db_index=True, help_text=b'An ISO-8601 date.'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='sent',
            field=models.BooleanField(help_text='Whether or not the reminder has been sent.', db_index=True,
                                      default=False),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='start_of_range',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, b'Popup'), (1, b'Email'), (2, b'Text')], db_index=True,
                                              default=0, help_text=b'A valid reminder type choice.'),
        ),
    ]
