# Generated by Django 2.0.5 on 2018-05-15 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_auto_20180403_2152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('start_date', 'title')},
        ),
        migrations.AlterModelOptions(
            name='coursegroup',
            options={'ordering': ('start_date', 'title')},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('start', 'title')},
        ),
        migrations.AlterModelOptions(
            name='homework',
            options={'ordering': ('start', 'title'), 'verbose_name_plural': 'Homework'},
        ),
    ]
