# Generated by Django 4.2.20 on 2025-09-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_auto_20180515_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'Popup'), (1, 'Email'), (2, 'Text'), (3, 'Push')], db_index=True, default=0, help_text='A valid reminder type choice.'),
        ),
    ]
