# Generated by Django 4.2.25 on 2025-10-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_alter_category_color_alter_course_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Owned'), (1, 'Rented'), (2, 'Ordered'), (3, 'Shipped'), (4, 'Need'), (5, 'Received'), (6, 'To Sell'), (7, 'Digital')], default=0, help_text='A valid material status choice.'),
        ),
    ]
