# Generated by Django 4.2.25 on 2025-10-30 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_alter_material_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursegroup',
            old_name='average_grade',
            new_name='overall_grade',
        ),
    ]
