# Generated by Django 4.2.25 on 2025-11-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_rename_average_grade_coursegroup_overall_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='is_online',
            field=models.BooleanField(default=False, help_text='Whether the course is online.'),
        ),
        migrations.AlterField(
            model_name='coursegroup',
            name='shown_on_calendar',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether items should be shown on the calendar.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='all_day',
            field=models.BooleanField(default=False, help_text='Whether it is an all day event.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='show_end_time',
            field=models.BooleanField(default=False, help_text='Whether the end time should be shown on the calendar.'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='all_day',
            field=models.BooleanField(default=False, help_text='Whether it is an all day event.'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='completed',
            field=models.BooleanField(default=False, help_text='Whether the homework has been completed.'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='show_end_time',
            field=models.BooleanField(default=False, help_text='Whether the end time should be shown on the calendar.'),
        ),
        migrations.AlterField(
            model_name='materialgroup',
            name='shown_on_calendar',
            field=models.BooleanField(default=True, help_text='Whether items should be shown on the calendar.'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='sent',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether the reminder has been sent.'),
        ),
    ]
