# Generated by Django 4.2.25 on 2025-11-05 23:17

from django.db import migrations, models
import helium.common.utils.commonutils
import helium.common.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0012_alter_course_is_online_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default=helium.common.utils.commonutils.random_color, help_text='A valid hex color code choice to determine the color items will be shown on the calendar.', max_length=7, validators=[helium.common.utils.validators.validate_hex_color]),
        ),
        migrations.AlterField(
            model_name='course',
            name='color',
            field=models.CharField(default=helium.common.utils.commonutils.random_color, help_text='A valid hex color code choice to determine the color events will be shown on the calendar.', max_length=7, validators=[helium.common.utils.validators.validate_hex_color]),
        ),
    ]
