# Generated by Django 4.2.26 on 2025-11-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0013_alter_category_color_alter_course_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='condition',
            field=models.PositiveIntegerField(choices=[(0, 'Brand New'), (1, 'Refurbished'), (2, 'Used - Like New'), (3, 'Used - Very Good'), (4, 'Used - Good'), (5, 'Used - Acceptable'), (6, 'Used - Poor'), (7, 'Broken'), (8, 'Digital')], default=0, help_text='A valid material condition choice.'),
        ),
    ]
