# Generated by Django 4.2.26 on 2025-11-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0014_alter_material_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroup',
            name='example_schedule',
            field=models.BooleanField(default=False, help_text='Whether it is part of the example schedule.'),
        ),
        migrations.AddField(
            model_name='event',
            name='example_schedule',
            field=models.BooleanField(default=False, help_text='Whether it is part of the example schedule.'),
        ),
        migrations.AddField(
            model_name='materialgroup',
            name='example_schedule',
            field=models.BooleanField(default=False, help_text='Whether it is part of the example schedule.'),
        ),
    ]
