# Generated by Django 4.2.26 on 2025-11-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0015_coursegroup_example_schedule_event_example_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'Popup'), (1, 'Email'), (2, 'Text')], db_index=True, default=0, help_text='A valid reminder type choice.'),
        ),
    ]
