# Generated by Django 4.2.26 on 2025-11-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0016_alter_reminder_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='dismissed',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether the reminder has been dismieed.'),
        ),
    ]
