# Generated by Django 4.2.26 on 2025-12-08 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0018_alter_reminder_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ('start_of_range', 'title')},
        ),
    ]
