# Generated by Django 4.2.26 on 2025-12-10 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0019_alter_reminder_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'Popup'), (1, 'Email'), (2, 'Text'), (3, 'Push')], db_index=True, default=0, help_text='A valid reminder type choice.'),
        ),
    ]
