# Generated by Django 4.2 on 2026-02-15 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0020_alter_reminder_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='repeating',
            field=models.BooleanField(default=False, help_text='Whether the reminder repeats (for courses).'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='course',
            field=models.ForeignKey(blank=True, help_text='The course with which to associate.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='planner.course'),
        ),
    ]
