# Generated by Django 4.2 on 2026-02-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0021_reminder_course_and_repeating'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroup',
            name='exceptions',
            field=models.TextField(blank=True, default='', help_text='Comma-separated dates (YYYYMMDD) when no classes occur (holidays, breaks).'),
        ),
        migrations.AddField(
            model_name='course',
            name='exceptions',
            field=models.TextField(blank=True, default='', help_text='Comma-separated dates (YYYYMMDD) when this course does not meet.'),
        ),
    ]
