# Generated by Django 4.2 on 2026-03-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0022_coursegroup_course_exceptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='notes',
            field=models.JSONField(blank=True, help_text='Rich text notes in Quill Delta format.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='notes',
            field=models.JSONField(blank=True, help_text='Rich text notes in Quill Delta format.', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='notes',
            field=models.JSONField(blank=True, help_text='Rich text notes in Quill Delta format.', null=True),
        ),
    ]
