# Generated by Django 4.2.29 on 2026-03-13 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0023_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseschedule',
            name='course',
            field=models.ForeignKey(help_text='The course with which to associate.', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='planner.course', unique=True),
        ),
    ]
