# Generated by Django 4.2.29 on 2026-03-13 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planner', '0024_courseschedule_unique_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, db_index=True, help_text='Display title for the note.', max_length=255)),
                ('content', models.JSONField(blank=True, help_text='Rich text content in Quill Delta format.', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='NoteLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, help_text='Linked event.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_links', to='planner.event')),
                ('homework', models.ForeignKey(blank=True, help_text='Linked homework assignment.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_links', to='planner.homework')),
                ('material', models.ForeignKey(blank=True, help_text='Linked material.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_links', to='planner.material')),
                ('note', models.ForeignKey(help_text='The note being linked.', on_delete=django.db.models.deletion.CASCADE, related_name='links', to='planner.note')),
            ],
        ),
        migrations.AddConstraint(
            model_name='notelink',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('event__isnull', True), ('homework__isnull', False), ('material__isnull', True)), models.Q(('event__isnull', False), ('homework__isnull', True), ('material__isnull', True)), models.Q(('event__isnull', True), ('homework__isnull', True), ('material__isnull', False)), _connector='OR'), name='notelink_exactly_one_entity'),
        ),
    ]
