# Generated by Django 4.2.29 on 2026-03-16

from django.db import migrations, models


def migrate_notelink_to_m2m(apps, schema_editor):
    """Migrate data from NoteLink table to new M2M fields on Note."""
    NoteLink = apps.get_model('planner', 'NoteLink')

    for link in NoteLink.objects.all():
        note = link.note
        if link.homework_id:
            note.homework.add(link.homework_id)
        if link.event_id:
            note.events.add(link.event_id)
        if link.resource_id:
            note.resources.add(link.resource_id)


def migrate_m2m_to_notelink(apps, schema_editor):
    """Reverse migration: recreate NoteLink entries from M2M fields."""
    Note = apps.get_model('planner', 'Note')
    NoteLink = apps.get_model('planner', 'NoteLink')

    for note in Note.objects.prefetch_related('homework', 'events', 'resources').all():
        for hw in note.homework.all():
            NoteLink.objects.create(note=note, homework=hw)
        for event in note.events.all():
            NoteLink.objects.create(note=note, event=event)
        for resource in note.resources.all():
            NoteLink.objects.create(note=note, resource=resource)


def clear_linked_note_titles(apps, schema_editor):
    """Set title to empty string for all notes that have linked entities."""
    Note = apps.get_model('planner', 'Note')

    # Notes with homework links
    Note.objects.filter(homework__isnull=False).update(title='')
    # Notes with event links
    Note.objects.filter(events__isnull=False).update(title='')
    # Notes with resource links
    Note.objects.filter(resources__isnull=False).update(title='')


def noop(apps, schema_editor):
    """No-op for reverse migration of title clearing (we can't restore old titles)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0032_add_example_schedule_to_note'),
    ]

    operations = [
        # Step 1: Add M2M fields to Note
        migrations.AddField(
            model_name='note',
            name='homework',
            field=models.ManyToManyField(
                blank=True,
                help_text='Linked homework assignments.',
                related_name='notes_set',
                to='planner.homework'
            ),
        ),
        migrations.AddField(
            model_name='note',
            name='events',
            field=models.ManyToManyField(
                blank=True,
                help_text='Linked events.',
                related_name='notes_set',
                to='planner.event'
            ),
        ),
        migrations.AddField(
            model_name='note',
            name='resources',
            field=models.ManyToManyField(
                blank=True,
                help_text='Linked resources (Material model).',
                related_name='notes_set',
                to='planner.material'
            ),
        ),

        # Step 2: Migrate data from NoteLink to M2M fields
        migrations.RunPython(migrate_notelink_to_m2m, migrate_m2m_to_notelink),

        # Step 3: Clear titles for notes with linked entities
        migrations.RunPython(clear_linked_note_titles, noop),

        # Step 4: Remove the constraint first
        migrations.RemoveConstraint(
            model_name='notelink',
            name='notelink_exactly_one_entity',
        ),

        # Step 5: Delete NoteLink model
        migrations.DeleteModel(
            name='NoteLink',
        ),
    ]
