# Generated by Django 4.2.29 on 2026-03-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0035_remove_duplicate_linked_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='dismissed',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether the reminder has been dismissed.'),
        ),
    ]
