# Generated by Django 4.2.30 on 2026-04-17 23:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0044_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('start_date', 'title'), 'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='coursegroup',
            options={'ordering': ('start_date', 'title'), 'verbose_name': 'Class group'},
        ),
        migrations.AlterModelOptions(
            name='courseschedule',
            options={'verbose_name': 'Class schedule'},
        ),
        migrations.AlterModelOptions(
            name='homework',
            options={'ordering': ('start', 'title'), 'verbose_name': 'Assignment'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ('title',), 'verbose_name': 'Resource'},
        ),
        migrations.AlterModelOptions(
            name='materialgroup',
            options={'ordering': ('title',), 'verbose_name': 'Resource group'},
        ),
        migrations.AlterField(
            model_name='category',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text="A decimal weight for this category's homework (note that all weights associated with a single course cannot exceed a value of 100).", max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='priority',
            field=models.PositiveIntegerField(default=50, help_text='A priority integer between 0 and 100.', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='homework',
            name='priority',
            field=models.PositiveIntegerField(default=50, help_text='A priority integer between 0 and 100.', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='offset',
            field=models.PositiveIntegerField(default=30, help_text='The number of units (in `offset_type`) from the offset.', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
