# Generated by Django 5.2.14 on 2026-05-11 16:33

import django.core.validators
import django.db.models.deletion
import helium.common.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0045_alter_course_options_alter_coursegroup_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(help_text='A display name. Must be unique within the parent course.', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateField(help_text='ISO-8601 date. Must be on-or-after `start_date`.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(help_text='ISO-8601 date. Must be on-or-before `end_date`.'),
        ),
        migrations.AlterField(
            model_name='coursegroup',
            name='end_date',
            field=models.DateField(help_text='ISO-8601 date. Must be on-or-after `start_date`.'),
        ),
        migrations.AlterField(
            model_name='coursegroup',
            name='start_date',
            field=models.DateField(help_text='ISO-8601 date. Must be on-or-before `end_date`.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(db_index=True, help_text='ISO-8601 datetime. Must be on-or-after `start`.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(db_index=True, help_text='ISO-8601 datetime. Must be on-or-before `end`.'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='category',
            field=models.ForeignKey(blank=True, default=None, help_text="The category to associate this homework with. If omitted or null, the homework is placed in the course's `Uncategorized` category (auto-created on first use).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homework', to='planner.category'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='completed',
            field=models.BooleanField(default=False, help_text='Whether the homework has been completed. Flipping this to `true` sets `completed_at` to the current time automatically.'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When the homework was first marked as completed. Set automatically the first time `completed` flips to `true`; not user-supplied.', null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='current_grade',
            field=models.CharField(help_text='Fraction of points earned in `"numerator/denominator"` form (e.g. `"25/30"`). Use `"-1/100"` to indicate ungraded.', max_length=255, validators=[helium.common.utils.validators.validate_fraction]),
        ),
        migrations.AlterField(
            model_name='homework',
            name='end',
            field=models.DateTimeField(db_index=True, help_text='ISO-8601 datetime. Must be on-or-after `start`.'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='start',
            field=models.DateTimeField(db_index=True, help_text='ISO-8601 datetime. Must be on-or-before `end`.'),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.JSONField(blank=True, help_text='Rich-text JSON (Quill Delta compatible). Setting this to empty on a note that has a linked entity deletes the note and returns 204.', null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='events',
            field=models.ManyToManyField(blank=True, help_text='Linked event. Mutually exclusive with `homework` and `resources` (see `homework` help).', related_name='notes_set', to='planner.event'),
        ),
        migrations.AlterField(
            model_name='note',
            name='homework',
            field=models.ManyToManyField(blank=True, help_text='Linked homework. A note may be linked to one homework, one event, or one resource — never more than one type, and never more than one entity within a type.', related_name='notes_set', to='planner.homework'),
        ),
        migrations.AlterField(
            model_name='note',
            name='resources',
            field=models.ManyToManyField(blank=True, help_text='Linked resource. Mutually exclusive with `homework` and `events` (see `homework` help).', related_name='notes_set', to='planner.material'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='offset',
            field=models.PositiveIntegerField(default=30, help_text='How far before the parent start time to fire, measured in `offset_type` units. Capped at 100.', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='start_of_range',
            field=models.DateTimeField(blank=True, help_text='Datetime the reminder fires. Server-computed from the parent (`event`, `homework`, or `course`) start time minus `offset × offset_type` whenever the parent or offset changes; do not send on create.', null=True),
        ),
    ]
