# Generated by Django 5.2.14 on 2026-05-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0046_alter_category_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Email'), (3, 'Push')], default=3, help_text='A valid reminder type choice.'),
        ),
    ]
