# Generated by Django 5.2.14 on 2026-05-13 13:58

import django.core.validators
import helium.common.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0046_alter_category_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text="Decimal in `[0, 100]`. Sum across a class's categories must be ≤ 100. A weight of `0` keeps the category organizational only; grade calc skips it. See `Course.has_weighted_grading` and https://heliumedu.freshdesk.com/support/solutions/articles/159000418648", max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.DecimalField(decimal_places=2, help_text='A decimal corresponding to credit hours; `"0.00"` is fine when unknown or N/A.', max_digits=4),
        ),
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(db_index=True, help_text='ISO-8601 datetime with offset. Must be on-or-after `start`.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='priority',
            field=models.PositiveIntegerField(default=50, help_text='Integer in `[0, 100]`, default `50`; should be stored in increments of 10. Suggested: `50` routine, `80` exam, `90` final.', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(db_index=True, help_text='ISO-8601 datetime with offset. Server normalizes to UTC and handles DST. Must be on-or-before `end`.'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='completed',
            field=models.BooleanField(default=False, help_text='Whether the assignment has been completed. Once `completed=true` and `current_grade` holds a real fraction (e.g. `"25/30"` or `"0/100"`), the assignment counts toward grade calc. For missed work: `completed=true`, `current_grade="0/<possible>"`. See https://heliumedu.freshdesk.com/support/solutions/articles/159000418648'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='current_grade',
            field=models.CharField(help_text='Fraction of points earned, `"numerator/denominator"` (e.g. `"25/30"`). `"-1/100"` marks the assignment ungraded. Pairs with `completed=true` to count toward grade calc.', max_length=255, validators=[helium.common.utils.validators.validate_fraction]),
        ),
        migrations.AlterField(
            model_name='homework',
            name='end',
            field=models.DateTimeField(db_index=True, help_text='ISO-8601 datetime with offset. Must be on-or-after `start`.'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='priority',
            field=models.PositiveIntegerField(default=50, help_text='Integer in `[0, 100]`, default `50`; should be stored in increments of 10. Suggested: `50` routine, `80` exam, `90` final.', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='homework',
            name='start',
            field=models.DateTimeField(db_index=True, help_text='ISO-8601 datetime with offset. Server normalizes to UTC and handles DST. Must be on-or-before `end`.'),
        ),
        migrations.AlterField(
            model_name='material',
            name='courses',
            field=models.ManyToManyField(blank=True, default=None, help_text='Classes that share this resource. May be empty.', related_name='materials', to='planner.course'),
        ),
    ]
