# Generated by Django 5.2.14 on 2026-05-13 15:35

from django.db import migrations, models


def backfill_teacher_email_nulls(apps, schema_editor):
    Course = apps.get_model('planner', 'Course')
    Course.objects.filter(teacher_email__isnull=True).update(teacher_email='')


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0047_alter_category_weight_alter_course_credits_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_teacher_email_nulls, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='course',
            name='room',
            field=models.CharField(blank=True, default='', help_text='An arbitrary string.', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher_email',
            field=models.EmailField(blank=True, default='', help_text='A valid email address.', max_length=254),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher_name',
            field=models.CharField(blank=True, default='', help_text='A display name for the teacher.', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='comments',
            field=models.TextField(blank=True, default='', help_text='An arbitrary string (which may contain HTML formatting).'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='comments',
            field=models.TextField(blank=True, default='', help_text='An arbitrary string (which may contain HTML formatting).'),
        ),
        migrations.AlterField(
            model_name='material',
            name='details',
            field=models.TextField(blank=True, default='', help_text='An arbitrary string (which may contain HTML formatting).'),
        ),
    ]
