# Generated by Django 5.2.14 on 2026-05-13 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0048_alter_course_room_alter_course_teacher_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text="Decimal in `[0, 100]`. Sum across a class's categories must be <= 100. A weight of `0` is organizational only when at least one category in the class has `weight > 0` (weighted mode); when no category has a non-zero weight, the class is points-based and every assignment contributes via its `current_grade` fraction regardless of category weight. See `Course.has_weighted_grading` and https://www.heliumedu.com/support/grades-and-progress/setting-up-weighted-grading-assignment-categories", max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='start_of_range',
            field=models.DateTimeField(blank=True, help_text='Datetime the reminder fires. Server-computed from the parent (`event`, `homework`, or `course`) start time minus `offset * offset_type` whenever the parent or offset changes; do not send on create.', null=True),
        ),
    ]
