# Generated by Django 5.2.14 on 2026-05-13 19:55

import django.core.validators
import helium.common.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0049_alter_category_weight_alter_reminder_start_of_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.DecimalField(decimal_places=2, help_text='A decimal corresponding to credit hours. If unknown or the syllabus doesn\'t specify, use `"0.00"`.', max_digits=4),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='days_of_week',
            field=models.CharField(default='0000000', help_text='Seven booleans (0 or 1) indicating which days of the week the course is on (week starts on Sunday). Authoritative — a `0` short-circuits event generation regardless of the per-day time fields. See "Common pitfalls" in the API description for the `00:00:00` off-day convention.', max_length=7, validators=[django.core.validators.RegexValidator('^[0-1]+$', 'Seven booleans (0 or 1) indicating which days of the week the course is on (week starts on Sunday).', 'invalid'), django.core.validators.MinLengthValidator(7, 'Seven booleans (0 or 1) indicating which days of the week the course is on (week starts on Sunday).')]),
        ),
        migrations.AlterField(
            model_name='homework',
            name='completed',
            field=models.BooleanField(default=False, help_text='Whether the homework has been completed. Once `completed=true` and `current_grade` holds a real fraction (e.g. `"25/30"` or `"0/100"`), the homework counts toward grade calc. For missed work: `completed=true`, `current_grade="0/<possible>"`. See https://heliumedu.freshdesk.com/support/solutions/articles/159000418648'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='current_grade',
            field=models.CharField(help_text='Fraction of points earned, `"numerator/denominator"` (e.g. `"25/30"`). `"-1/100"` marks the assignment ungraded; on an ungraded row, the denominator is the expected point value when graded — within-category weighting is handled by `Category.weight`, not by per-assignment denominators. Pairs with `completed=true` to count toward grade calc.', max_length=255, validators=[helium.common.utils.validators.validate_fraction]),
        ),
    ]
