# Generated by Django 5.2.14 on 2026-05-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0051_event_recurrence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='start_of_range',
            field=models.DateTimeField(blank=True, help_text='Datetime the reminder fires. Server-derived from the parent (`event` / `homework` / `course`) start time minus `offset * offset_type`. Read-only.', null=True),
        ),
    ]
