# Generated by Django 5.2.14 on 2026-05-17 16:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0053_alter_reminder_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text="Sum across a class's categories must be <= 100. A weight of `0` is organizational only when at least one category in the class has `weight > 0` (weighted mode); when no category has a non-zero weight, the class is points-based and every assignment contributes via its `current_grade` fraction regardless of category weight. See `Course.has_weighted_grading` and https://heliumedu.freshdesk.com/support/solutions/articles/159000418648", max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='priority',
            field=models.PositiveIntegerField(default=50, help_text='Should be stored in increments of 10. Suggested: `50` routine, `80` exam, `90` final.', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='homework',
            name='priority',
            field=models.PositiveIntegerField(default=50, help_text='Should be stored in increments of 10. Suggested: `50` routine, `80` exam, `90` final.', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='material',
            name='condition',
            field=models.PositiveIntegerField(choices=[(0, 'Brand New'), (1, 'Refurbished'), (2, 'Used - Like New'), (3, 'Used - Very Good'), (4, 'Used - Good'), (5, 'Used - Acceptable'), (6, 'Used - Poor'), (7, 'Broken'), (8, 'Digital')], default=0, help_text='The physical condition of the resource.'),
        ),
        migrations.AlterField(
            model_name='material',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Owned'), (1, 'Rented'), (2, 'Ordered'), (3, 'Shipped'), (4, 'Need'), (5, 'Received'), (6, 'To Sell'), (7, 'Digital')], default=0, help_text='The lifecycle status of the resource.'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='offset',
            field=models.PositiveIntegerField(default=30, help_text='How far before the parent start time to fire, measured in `offset_type` units.', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='offset_type',
            field=models.PositiveIntegerField(choices=[(0, 'minutes'), (1, 'hours'), (2, 'days'), (3, 'weeks')], default=0, help_text='The unit applied to `offset`.'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Email'), (3, 'Push')], default=3, help_text='The notification channel for this reminder.'),
        ),
    ]
