# Generated by Django 5.2.14 on 2026-05-30 23:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0053_alter_category_weight_alter_event_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text="Sum across a class's categories must be <= 100. A weight of `0` is organizational only when at least one category in the class has `weight > 0` (weighted mode); when no category has a non-zero weight, the class is points-based and every assignment contributes via its `current_grade` fraction regardless of category weight. See `Course.has_weighted_grading` and https://www.heliumedu.com/support/grades-and-progress/setting-up-weighted-grading-assignment-categories.", max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='priority',
            field=models.PositiveIntegerField(default=50, help_text='Should be stored in increments of 10.', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='homework',
            name='completed',
            field=models.BooleanField(default=False, help_text='Whether the homework has been completed. Once `completed=true` and `current_grade` holds a real fraction (e.g. `"25/30"` or `"0/100"`), the homework counts toward grade calc. For missed work: `completed=true`, `current_grade="0/<possible>"`. See https://www.heliumedu.com/support/grades-and-progress/setting-up-weighted-grading-assignment-categories.'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='priority',
            field=models.PositiveIntegerField(default=50, help_text='Should be stored in increments of 10.', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
