# Generated by Django 5.2.14 on 2026-06-03 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0054_alter_category_weight_alter_event_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='course',
            field=models.ForeignKey(blank=True, help_text='The course with which to associate (mutually exclusive with `event` and `homework`).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='planner.course'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='event',
            field=models.ForeignKey(blank=True, help_text='The event with which to associate (mutually exclusive with `course` and `homework`).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='planner.event'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='homework',
            field=models.ForeignKey(blank=True, help_text='The homework with which to associate (mutually exclusive with `course` and `event`).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='planner.homework'),
        ),
        migrations.AlterField(
            model_name='material',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Owned'), (1, 'Rented'), (2, 'Ordered'), (3, 'Shipped'), (4, 'Need'), (5, 'Received'), (6, 'To Sell'), (7, 'Digital')], default=0, help_text='The status of the resource.'),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.JSONField(blank=True, help_text='Rich-text JSON ([Quill Delta format](https://quilljs.com/docs/delta/)).', null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='events',
            field=models.ManyToManyField(blank=True, help_text='The event with which to associate (if linked, mutually exclusive with `homework` and `resources`).', related_name='notes_set', to='planner.event'),
        ),
        migrations.AlterField(
            model_name='note',
            name='homework',
            field=models.ManyToManyField(blank=True, help_text='The homework with which to associate (if linked, mutually exclusive with `events` and `resources`).', related_name='notes_set', to='planner.homework'),
        ),
        migrations.AlterField(
            model_name='note',
            name='resources',
            field=models.ManyToManyField(blank=True, help_text='The material with which to associate (if linked, mutually exclusive with `homework` and `events`).', related_name='notes_set', to='planner.material'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='course',
            field=models.ForeignKey(blank=True, help_text='The course with which to associate (mutually exclusive with `homework` and `event`).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='planner.course'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='event',
            field=models.ForeignKey(blank=True, help_text='The event with which to associate  (mutually exclusive with `homework` and `course`).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='planner.event'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='homework',
            field=models.ForeignKey(blank=True, help_text='The homework with which to associate (mutually exclusive with `event` and `course`).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='planner.homework'),
        ),
    ]
