# Generated by Django 5.2.14 on 2026-06-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0055_alter_attachment_course_alter_attachment_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='owner_id',
            field=models.CharField(blank=True, help_text='An arbitrary string identifying the owning entity.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='condition',
            field=models.PositiveIntegerField(choices=[(0, 'Brand New'), (1, 'Refurbished'), (2, 'Used - Like New'), (3, 'Used - Very Good'), (4, 'Used - Good'), (5, 'Used - Acceptable'), (6, 'Used - Poor'), (7, 'Broken'), (8, 'Digital')], default=0, help_text='The physical condition of the material.'),
        ),
        migrations.AlterField(
            model_name='material',
            name='courses',
            field=models.ManyToManyField(blank=True, default=None, help_text='Classes that share this material. May be empty.', related_name='materials', to='planner.course'),
        ),
        migrations.AlterField(
            model_name='material',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Owned'), (1, 'Rented'), (2, 'Ordered'), (3, 'Shipped'), (4, 'Need'), (5, 'Received'), (6, 'To Sell'), (7, 'Digital')], default=0, help_text='The status of the material.'),
        ),
    ]
