# Generated by Django 5.2.16 on 2026-08-06 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0058_backfill_deprecated_reminder_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseschedule',
            name='course',
            field=models.ForeignKey(help_text='The course with which to associate.', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='planner.course'),
        ),
    ]
