# Generated by Django 5.2.16 on 2026-08-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0060_seed_default_categories_for_categoryless_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseschedule',
            name='anchor_date',
            field=models.DateField(blank=True, help_text='ISO-8601 date a rotation is anchored to.', null=True),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='cycle_length',
            field=models.PositiveSmallIntegerField(blank=True, help_text='The number of school days in one rotation cycle (mutually exclusive with `week_interval`).', null=True),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='cycle_slots',
            field=models.JSONField(blank=True, help_text='A day-based cycle\'s meeting times keyed by cycle-day index, as a list of `{"indices": [...], "start_time": "HH:MM:SS", "end_time": "HH:MM:SS"}`.', null=True),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='end_date',
            field=models.DateField(blank=True, help_text="ISO-8601 date for schedule end override; when not set, the course's `end_date` is used.", null=True),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='start_date',
            field=models.DateField(blank=True, help_text="ISO-8601 date for schedule start override; when not set, the course's `start_date` is used.", null=True),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='template',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Weekly'), (1, 'A/B Day'), (2, '6-Day Cycle'), (3, '8-Day Cycle'), (4, 'Week A/B')], help_text='The template this schedule was created from.', null=True),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='week_interval',
            field=models.PositiveSmallIntegerField(blank=True, help_text='The number of weeks in one rotation for a week-based schedule (mutually exclusive with `cycle_length`).', null=True),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='week_offset',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Which week of the rotation this schedule meets, counted from `anchor_date`'s week.", null=True),
        ),
        migrations.AddConstraint(
            model_name='courseschedule',
            constraint=models.CheckConstraint(condition=models.Q(('cycle_length__isnull', False), ('week_interval__isnull', False), _negated=True), name='courseschedule_single_rotation_type'),
        ),
    ]
