# Generated by Django 5.2.16 on 2026-08-07 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0060_seed_default_categories_for_categoryless_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseschedule',
            name='anchor_date',
            field=models.DateField(blank=True, help_text='The calendar date that is cycle "Day 1". Required when `cycle_length` is set, otherwise null.', null=True),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='cycle_length',
            field=models.PositiveSmallIntegerField(blank=True, help_text='For a rotating/A-B/block schedule, the number of school days in one cycle (2 for A/B). Null for an ordinary weekly schedule, in which case `days_of_week` and the per-weekday time fields apply instead.', null=True),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='cycle_slots',
            field=models.JSONField(blank=True, help_text='For a cycle schedule, a list of `{"indices": [<1-based cycle-day indices sharing a time>], "start_time": "HH:MM:SS", "end_time": "HH:MM:SS"}` objects — the variable-length analogue of the per-weekday time fields. Null for a weekly schedule.', null=True),
        ),
    ]
