# Generated by Django 5.2.16 on 2026-08-10 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0062_remove_courseschedule_courseschedule_single_rotation_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='event',
            field=models.ForeignKey(blank=True, help_text='The event with which to associate (mutually exclusive with `homework` and `course`).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='planner.event'),
        ),
    ]
