# Generated by Django 5.2.17 on 2026-08-30 19:15

from django.db import migrations, models
from django.db.models.functions import Length, Substr


def truncate_long_messages(apps, schema_editor):
    """Trim messages that predate the cap so the column narrowing can't fail.

    Under a strict `sql_mode` the ALTER aborts on the first over-long row rather than trimming it.
    """
    Reminder = apps.get_model('planner', 'Reminder')

    (Reminder.objects
     .annotate(message_length=Length('message'))
     .filter(message_length__gt=255)
     .update(message=Substr('message', 1, 255)))


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0066_fix_note_newline_termination'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ('start_of_range', 'message')},
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='title',
        ),
        migrations.RunPython(truncate_long_messages, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='reminder',
            name='message',
            field=models.CharField(help_text='A string that will be used as the reminder message.', max_length=255),
        ),
    ]
