# Generated by Django 5.2.17 on 2026-08-30 21:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0067_alter_reminder_options_remove_reminder_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.DecimalField(decimal_places=2, help_text='A decimal corresponding to credit hours. If unknown or the syllabus doesn\'t specify, use `"0.00"`.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
