# Generated by Django 5.2.17 on 2026-09-06 04:59

import logging

from django.conf import settings
from django.db import migrations, models

logger = logging.getLogger(__name__)


def drop_duplicate_active_series(apps, schema_editor):
    """Collapse each course series to a single active reminder before the index is built.

    MySQL never created the conditional UniqueConstraint this replaces, so production may hold
    duplicates that would make the new index fail to apply. The lowest pk in each series is kept.
    """
    Reminder = apps.get_model('planner', 'Reminder')

    seen = set()
    duplicate_pks = []
    for pk, *series_key in (Reminder.objects
                            .filter(course__isnull=False, sent=False, dismissed=False)
                            .order_by('pk')
                            .values_list('pk', 'course_id', 'user_id', 'type', 'offset',
                                         'offset_type')
                            .iterator(chunk_size=2000)):
        key = tuple(series_key)
        if key in seen:
            duplicate_pks.append(pk)
        else:
            seen.add(key)

    logger.info(f'{len(seen)} active course reminder series, '
                f'{len(duplicate_pks)} duplicate(s) to remove.')

    if duplicate_pks:
        Reminder.objects.filter(pk__in=duplicate_pks).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0068_alter_course_credits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(drop_duplicate_active_series, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='reminder',
            name='reminder_one_active_per_course_series',
        ),
        migrations.AddField(
            model_name='reminder',
            name='active_course_series',
            field=models.GeneratedField(db_persist=False, expression=models.Case(models.When(dismissed=False, sent=False, then=models.F('course')), default=models.Value(None), output_field=models.BigIntegerField()), output_field=models.BigIntegerField(null=True)),
        ),
        migrations.AddConstraint(
            model_name='reminder',
            constraint=models.UniqueConstraint(fields=('active_course_series', 'user', 'type', 'offset', 'offset_type'), name='reminder_one_active_per_course_series'),
        ),
    ]
