# Generated by Django 5.2.17 on 2026-09-17 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0069_reminder_active_course_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='materials',
            field=models.ManyToManyField(blank=True, default=None, help_text='A list of resources with which to associate.', related_name='homework', to='planner.material'),
        ),
        migrations.AlterField(
            model_name='material',
            name='condition',
            field=models.PositiveIntegerField(choices=[(0, 'Brand New'), (1, 'Refurbished'), (2, 'Used - Like New'), (3, 'Used - Very Good'), (4, 'Used - Good'), (5, 'Used - Acceptable'), (6, 'Used - Poor'), (7, 'Broken'), (8, 'Digital')], default=0, help_text='The physical condition of the resource.'),
        ),
        migrations.AlterField(
            model_name='material',
            name='courses',
            field=models.ManyToManyField(blank=True, default=None, help_text='Classes that share this resource. May be empty.', related_name='materials', to='planner.course'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_group',
            field=models.ForeignKey(help_text='The resource group with which to associate.', on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='planner.materialgroup'),
        ),
        migrations.AlterField(
            model_name='material',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Owned'), (1, 'Rented'), (2, 'Ordered'), (3, 'Shipped'), (4, 'Need'), (5, 'Received'), (6, 'To Sell'), (7, 'Digital')], default=0, help_text='The status of the resource.'),
        ),
        migrations.AlterField(
            model_name='note',
            name='resources',
            field=models.ManyToManyField(blank=True, help_text='The resource with which to associate (if linked, mutually exclusive with `homework` and `events`).', related_name='notes_set', to='planner.material'),
        ),
    ]
