# Generated by Django 5.2.17 on 2026-10-01 12:58

import helium.common.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0070_resource_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='current_grade',
            field=models.CharField(help_text='Fraction of points earned, `"numerator/denominator"` (e.g. `"25/30"`). `"-1/100"` marks the assignment ungraded. Within-category weighting is handled by `Category.weight`, not by per-assignment denominators. Pairs with `completed=true` to count toward grade calc.', max_length=255, validators=[helium.common.utils.validators.validate_fraction]),
        ),
    ]
