from .base import BaseModel
from .emailreputationevent import (
    EmailReputationEvent,
    EMAIL_TYPE_VERIFICATION,
    EMAIL_TYPE_REGISTRATION,
    EMAIL_TYPE_PASSWORD_RESET,
    EMAIL_TYPE_DORMANT_WARNING,
    EMAIL_TYPE_REMINDER,
    EMAIL_TYPE_UNKNOWN,
    EMAIL_TYPE_CHOICES,
    EVENT_TYPE_BOUNCE,
    EVENT_TYPE_COMPLAINT,
    EVENT_TYPE_CHOICES,
    BOUNCE_SUBTYPE_PERMANENT,
    BOUNCE_SUBTYPE_TRANSIENT,
    BOUNCE_SUBTYPE_UNDETERMINED,
    COMPLAINT_SUBTYPE_ABUSE,
    COMPLAINT_SUBTYPE_AUTH_FAILURE,
    COMPLAINT_SUBTYPE_FRAUD,
    COMPLAINT_SUBTYPE_NOT_SPAM,
    COMPLAINT_SUBTYPE_OTHER,
    COMPLAINT_SUBTYPE_VIRUS,
)
from .emailreputationsummary import EmailReputationSummary
